def raise_exception_msg(message=""):
    try:
        print(a)
    except NameError as e:
        print(message)